### PR TITLE
Feature 9 listen to space

### PR DESCRIPTION
**Pull request by sarxhlwalker**
removing input data in interactor constructor for playspace

### CODE REVIEW

**Review by rafaelgacesa — APPROVED** [review]
This is excellent

**Review by SiqiZhang6 — APPROVED** [review]
Looks awesome, thanks!

**Review by Mistryr222 — CHANGES_REQUESTED** [review]
This looks good.

**Review by Mistryr222 — APPROVED** [review]
Great Work :D !

**Pull request merged**
