### PR TITLE
Actual Song Cover Fix

### PR DESCRIPTION
**Pull request by chrstinalin**

### CODE REVIEW

**Comment by rafaelgacesa** [comment]
Fixed the default cover in two ways:
1. fixed the file path issue
2. made default cover an instance variable of the singleton so it only loads the image once (in the constructor) since `ImageIO.read()` is **__slow__** (~1 second to load library vs. ~10 seconds reading it for every song)

Please lmk if this is all ok by you @chrstinalin

**Review by rafaelgacesa — APPROVED** [review]
After making some small changes, looks good to me.

**Comment by chrstinalin** [comment]
Definitely a good change by me

**Review by sarxhlwalker — APPROVED** [review]
no complaints here

**Review by manya-mittal — APPROVED** [review]
looks good to me

**Review by SiqiZhang6 — APPROVED** [review]
lmao what is happening with the comments, looks great tho

**Pull request merged**
