### PR TITLE
Mini update

### PR DESCRIPTION
**Pull request by chrstinalin**
- Covers!
- tests yay :)

### CODE REVIEW

**Review by rafaelgacesa — APPROVED** [review]
This mini update is so compact!

**Review by manya-mittal — APPROVED** [review]
Lots of changes but looks good to me

**Review by sarxhlwalker — APPROVED** [review]
u did great thanks for ur incredible database skills

**Review by rafaelgacesa — DISMISSED** [review]
Approved. Again

**Review by sarxhlwalker — APPROVED** [review]
thanks for the tests

**Review by manya-mittal — APPROVED** [review]
Thanks for removing conflicts ! soooo goood

**Review by rafaelgacesa — APPROVED** [review]

**Review by sarxhlwalker — APPROVED** [review]

**Review by manya-mittal — APPROVED** [review]
autograder works yay

**Pull request merged**
