### PR TITLE
Added unit tests for my use cases, controller

### PR DESCRIPTION
**Pull request by rafaelgacesa**
### In this pull:
- unit testing for play song, recommend song, pause song, skip song, and the engine controller
- minor changes to classes (mostly typos, warnings, etc.)

### CODE REVIEW

**Review by chrstinalin — APPROVED** [review]
Yay testing 😁

**Review by sarxhlwalker — APPROVED** [review]
wow so testy

**Review by NicholasMacasaet — DISMISSED** [review]

**Comment by rafaelgacesa** [comment]
Had to update to conform to https://github.com/CSC207-2022F-UofT/course-project-team-communify/pull/73

**Review by sarxhlwalker — APPROVED** [review]
looks good thanks for the test files

**Comment by rafaelgacesa** [comment]
Side note: this should be merged after https://github.com/CSC207-2022F-UofT/course-project-team-communify/pull/76 and https://github.com/CSC207-2022F-UofT/course-project-team-communify/pull/75, even if it has three reviews before then.

Just to make sure there's no terrible conflicts, since this code is not critical.

**Review by chrstinalin — APPROVED** [review]

**Review by SiqiZhang6 — DISMISSED** [review]
Thanks for the tests, i believe #76 and #75 are merged

**Review by sarxhlwalker — APPROVED** [review]
wow so testy x2. thanks for dealing w the autograder

**Review by chrstinalin — APPROVED** [review]
Yay for re-reviews

**Pull request merged**
