### PR TITLE
Feature 5 playlist curation ver2

### PR DESCRIPTION
**Pull request by NicholasMacasaet**
Some minor cleaning up of code done. Both use cases have been successfully integrated into view. Bug with creating playlist from search bar fixed

### CODE REVIEW

**Review by rafaelgacesa — APPROVED** [review]
Looks good to me!

**Review by sarxhlwalker — APPROVED** [review]
lgtm

**Comment by rafaelgacesa** [comment]
Looks good to me!

**Review by sarxhlwalker — APPROVED** [review]
looks great

**Review by rafaelgacesa — APPROVED** [review]

**Review by manya-mittal — APPROVED** [review]
looks great!

**Pull request merged**
