### PR TITLE
songLibrary Persistence

### PR DESCRIPTION
**Pull request by chrstinalin**
Added windowClosingListener to save songLibrary once window is closed.

### CODE REVIEW

**Review by sarxhlwalker — APPROVED** [review]
looks good to me. if you want you can add a comment in windowClosing() to explain why it's OK to call save library in the view (cause both in blue layer), but not necessary.

**Review by sarxhlwalker — APPROVED** [review]
comment good nice indeed.

**Review by rafaelgacesa — APPROVED** [review]
Nice! Good use of listeners.

**Review by SiqiZhang6 — APPROVED** [review]
awesome tysm

**Pull request merged**
