### PR TITLE
Look & Feel Dependency

### PR DESCRIPTION
**Pull request by chrstinalin**
Adding FlatLaf as dependency and subsequent call in main().

make program look good :thumbs-up:

### CODE REVIEW

**Review by rafaelgacesa — DISMISSED** [review]
Just a new dependency

**Review by sarxhlwalker — DISMISSED** [review]
looks good

**Review by NicholasMacasaet — APPROVED** [review]

**Review by sarxhlwalker — APPROVED** [review]
cute icons!

**Review by NicholasMacasaet — APPROVED** [review]

**Review by SiqiZhang6 — APPROVED** [review]
looks great, tysm

**Pull request merged**
