### PR TITLE
Edit playlist use case updated

### PR DESCRIPTION
**Pull request by NicholasMacasaet**
Updating use case to be in line with implementations for other use cases.

### CODE REVIEW

**Review by sarxhlwalker — DISMISSED** [review]
Overall looks good. No complaints here.

**Review by rafaelgacesa — APPROVED** [review]
Agree with Sarah, this code looks good.

**Review by rafaelgacesa — APPROVED** [review]
Stupid merge conflict import statement.

**Review by rafaelgacesa — APPROVED** [review]

**Review by sarxhlwalker — APPROVED** [review]
thanks for fixing merge conflicts

**Review by chrstinalin — APPROVED** [review]
Thumbs up

**Pull request merged**
